### ISSUE TITLE
bump minimum PHP requirement

### ISSUE THREAD

**Issue by lsmith77** [symfony-cmf/symfony-cmf#220]
symfony/symfony requires 5.3.9, imho we should also make that our minimal requirement at the very least.

related see also
```
09:29 <WouterJ> PublishWorkflow contains a pretty big bug when used in PHP <=5.3.6
09:29 <WouterJ> (making non-published articles still visible for everyone)
09:29 <WouterJ> this means that the bundle wasn't used on PHP <=5.3.6 before (as people would have noticed it)
09:31 <WouterJ> should we consider it a security leak and fix it in all versions? Or should we consider it to be a normal bug and fix it in 1.2 and master only? (or should we just make the PHP requirement higher?)
10:52 <@lsmith> WouterJ: what bug in PublishWorkflow?
11:02 <WouterJ> lsmith, the voters use is_subclass_of to check if the document implements PublishableInterface or the PublishTimePeriodReadInterface. is_subclass_of doesn't support checks for interfaces before PHP 5.3.7
11:02 <WouterJ> this means that the voters end with ACCESS_ABSTRAIN, resulting in a none published document being shown
11:03 <WouterJ> see for instance https://travis-ci.org/symfony-cmf/SeoBundle/jobs/64817836#L509
```

**Comment by lsmith77** [comment]
@WouterJ / @dbu / @dantleech

**Comment by dantleech** [comment]
No objections. I think it makes sense to go with the Symfony minimum requirements.

**Comment by dbu** [comment]
:+1: no point in supporting older versions of php than symfony itself.

**Comment by lsmith77** [comment]
so we do this in the next minor/major versions? what about the issue @WouterJ noted in the above IRC chat log?

**Comment by dbu** [comment]
i think adding a warning to not use this with too old versions of php anymore is good enough. people with old versions of the bundle and php will just get no more updates when running composer update. if they don't read warnings, they will not notice the problem either way.

what we could do is add a check in the DI extension of older versions of CoreBundle (and *not* bump the minimum php version there) that checks whether the workflow is activated and php is too old and in that case raises an exception. that way people who update will get the new version and see an error and hopefully start updating their php rather than roll back to the old version...

**Comment by lsmith77** [comment]
sounds like a plan ..

I just bumped the min PHP version in master in all repos but RoutingAuto, RoutingAutoBundle, ResourceBundle, ResourceRestBundle because these currently do not have a PHP dependency at all. IMHO we should add a dependency there however .. wdyt? or should be instead rely on a transitive PHP dep unless we need something specifically higher .. imho no

**Comment by dbu** [comment]
> should add a dependency there however .. wdyt? or should be instead rely
> on a transitive PHP dep unless we need something specifically higher ..
> imho no

lets be explicit there as well.

**Comment by dbu** [comment]
see https://github.com/symfony-cmf/CoreBundle/pull/175
