### ISSUE TITLE
An error has occurred during update static content on other language

### ISSUE THREAD

**Issue by maity-kgz** [symfony-cmf/symfony-cmf#230]
Error  occuring while trying to edit and update static content from sonata admin panel by clicking on one of the 'flags'.
Steps to recreate error:

1. Go to admin panel
2. Click on left menu Content/Static Content/The Company
3. Click on one of the flags on right-top corner  (De, Fr)
4. Edit content
5. Click UPDATE

And here error occures.
**The problem can be duplicated on DEMO site too !!!**

**Comment by maity-kgz** [comment]
Error occurs even if you just click on UPDATE button without any action.

1. Go to admin panel
2. Select some static content 
3. Click UPDATE

**Comment by ElectricMaxxx** [comment]
You have got an Exception or StackTrace?

**Comment by maity-kgz** [comment]
Seems like I posted on a wrong place, I should report this problem on SonataAdmin.
There is no Exception or StackTrace.
The error is showed on FLASH BANNER in admin panel.
Exact text is:  "An error has occurred during update of item "The Company".

**Comment by dbu** [comment]
have a look at the app/logs/dev.log to see if you find something there?

**Comment by maity-kgz** [comment]
You can duplicate this in DEMO site too. Have a look there if you want.
Noting interesting in dev.log
Only this translation warning.
[2016-02-12 17:01:34] translation.WARNING: Translation not found. {"id":"An error has occurred during update of item \"The Company\".","domain":"SonataAdminBundle","locale":"en"}

**Comment by WouterJ** [comment]
Seems like this is the same issue as reported in https://github.com/symfony-cmf/cmf-sandbox/issues/316 and this is due to a bug in SonataDoctrinePhpcrAdminBundle. I submitted a fix here: https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/360 I hope this can be emrged + released quickly.

Thanks for your quick responses and the report @maity-kgz! Let me know if that change fixed it for you locally as well

**Comment by maity-kgz** [comment]
@WouterJ doctrine-phpcr-admin-bundle 1.2.6 fixes this issue. Thanx!
